language: android
android:
    components:
        - tools
        - build-tools-23.0.1
        - platform-tools
        - android-23
        - extra
script:
 - ./gradlew assembleDebug
mvn install -B
