language: android
android:
    components:
        - tools
        - build-tools-23.0.1
        - platform-tools
        - android-23
        - extra
before_install:
 - chmod +x gradlew
script:
 -./gradlew build connectedCheck
mvn install -B
