language: android
jdk:
    - oraclejdk7
android:
    components:
        - tools
        - build-tools-23.0.1
        - platform-tools
        - android-23
before_install:
 - chmod +x gradlew
script:
 - ./gradlew assembleDebug
